### PR TITLE
Make Rosé Pine Moon's "Toolbar Field Highlight" contrast better

### PR DESCRIPTION
**Pull request by Starcr0ss**
Revised "Rosé Pine Moon" for better contrasting "Toolbar Field Highlight"

### CODE REVIEW

**Comment by mvllow** [comment]
Thank you for the pull request! Would it make sense to apply these same changes to the main and dawn variants as well?

**Comment by Starcr0ss** [comment]
> Thank you for the pull request! Would it make sense to apply these same changes to the main and dawn variants as well?

So sorry for the long delay. I've been meaning to get to this for a while but was too busy.
I tested out each theme and it seems that there are only contrast issues for "Rose Pine" and "Rose Pine Moon". Applying the change to only Moon and main is the best tweak.
"Rose Pine Dawn" is perfect as is, so you can leave that variant alone.

**Comment by mvllow** [comment]
No worries! We'll merge as is then, thank you :)

**Comment by Starcr0ss** [comment]
> No worries! We'll merge as is then, thank you :)

Okay great, and I can see about fixing the main variant's highlight color as well. Expect another merge request for that one as well.

**Pull request merged**
